---
all:
  children:

    client_apps:
      hosts:

        alpha:
          ansible_host: ssh-service-alpha.client-apps1.svc.cluster.local
# all:
#   children:
#     webservers:
#       hosts:
#         app01.example.com:
#           ansible_user: deploy
#   vars:
#     ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
