---
- name: Install Python 3 on Alpine Linux
  hosts: all
  gather_facts: false  # Prevents Ansible from needing Python before it's installed

  tasks:
    - name: Bootstrap Python 3 on Alpine using raw command
      ansible.builtin.raw: apk add --no-cache python3
      become: true
      changed_when: false

    - name: Update Alpine package index and install packages
      become: true
      community.general.apk:
        name:
          - python3
        state: present
        update_cache: true

    - name: Check Python 3 version
      ansible.builtin.command: python3 --version
      register: python_version
      become: true